# Site settings
name: Jack Duong
author: Jack Duong
title: Storm Coder
email: son.jack0218@gmail.com
description: A blog about my journey in learning web development
baseurl: "" 
url: "http://imrjack.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  imrjack

# Build settings
markdown: kramdown
permalink: pretty

# pagination

paginate: 7
